{% set name = "scitiff" %}
{% set version = "25.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scitiff-{{ version }}.tar.gz
  sha256: 8461ac7be6c5124be146d8bc98798b277721f731766c4b9d8a39bbb25e47d50b

build:
  entry_points:
    - scitiff-dev-dump-schemas = scitiff._schema:dump_schemas
    - scitiff-dump-metadata-example = scitiff.executables:dump_metadata_example
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - scipp
    - tifffile
    - jsonschema
    - pydantic

test:
  imports:
    - scitiff
  commands:
    - pip check
    - scitiff-dev-dump-schemas --help
    - scitiff-dump-metadata-example --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://scipp.github.io/scitiff/
  summary: Scientific tiff format for imaging experiments.
  description: |
    SciTiff format inherits HyperStacks and define metadata on top of the HyperStacks.
    Scitiff project hosts both metadata schema and io helpers to save/load scitiff images.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://scipp.github.io/scitiff/
  dev_url: https://github.com/scipp/scitiff

extra:
  recipe-maintainers:
    - YooSunYoung
